
export  const LOGIN_REQUEST = 'LOGIN_REQUEST'
export  const LOGIN_INPROGRASS = 'LOGIN_INPROGRASS'
export  const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER'
export  const LOGIN_ERROR = 'LOGIN_ERROR'

export  const  SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export  const SIGNUP_INPROGRASS = 'SIGNUP_INPROGRASS'
export  const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export  const SIGNUP_ERROR = 'SIGNUP_ERROR'



export default {
    LOGIN_REQUEST,
    LOGIN_INPROGRASS,
    LOGIN_SUCCESS_USER,
    LOGIN_ERROR,
    SIGNUP_REQUEST,
    SIGNUP_INPROGRASS,
    SIGNUP_SUCCESS,
    SIGNUP_ERROR
}
  

