export const COMPLAINT_REQUEST = "COMPLAINT_REQUEST";
export const COMPLAINT_INPROGRASS = "COMPLAINT_INPROGRASS";
export const COMPLAINT_SUCCESS = "COMPLAINT_SUCCESS";
export const COMPLAINT_ERROR = "COMPLAINT_ERROR";

export const ACCOUNT_REGISTER_REQUEST = "ACCOUNT_REGISTER_REQUEST";
export const ACCOUNT_REGISTER_INPROGRASS = "ACCOUNT_REGISTER_INPROGRASS";
export const ACCOUNT_REGISTER_SUCCESS = "ACCOUNT_REGISTER_SUCCESS";
export const ACCOUNT_REGISTER_ERROR = "ACCOUNT_REGISTER_ERROR";



export const NOTIFICATION_REGISTER_REQUEST = "NOTIFICATION_REGISTER_REQUEST";
export const NOTIFICATION_INPROGRASS = "NOTIFICATION_INPROGRASS";
export const NOTIFICATION_REGISTER_SUCCESS = "NOTIFICATION_REGISTER_SUCCESS";
export const NOTIFICATION_REGISTER_ERROR = "NOTIFICATION_REGISTER_ERROR";


export default {
  COMPLAINT_REQUEST,
  COMPLAINT_INPROGRASS,
  COMPLAINT_SUCCESS,
  COMPLAINT_ERROR,
  ACCOUNT_REGISTER_REQUEST,
  ACCOUNT_REGISTER_INPROGRASS,
  ACCOUNT_REGISTER_SUCCESS,
  ACCOUNT_REGISTER_ERROR,
  NOTIFICATION_REGISTER_REQUEST,
  NOTIFICATION_INPROGRASS,
  NOTIFICATION_REGISTER_SUCCESS,
  NOTIFICATION_REGISTER_ERROR
};
